### ISSUE TITLE
No module named 'bot.utils.tg_manager.TGSession'

### ISSUE THREAD

**Issue by tuanteku9x** [Desamod/TVerseBot#1]
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

**Comment by Desamod** [comment]
OS / Python version?

**Comment by tuanteku9x** [comment]
I'm using: windows 10, python 3.10 3.11
Code: pip install python-telegram-bot --upgrade
but still error

**Comment by Desamod** [comment]
Check your python version when you running bot, must be  3.10

**Comment by tuanteku9x** [comment]
Thanks, I've uninstall 3.11 then pip install -r requirements.txt
It's working fine now
